<!DOCTYPE html>
<html>
<head>
    <title>Daftar Hadir</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<style type="text/css">
    table tr td,
    table tr th{
        font-size: 9pt;
    }
</style>
<center>
    <p>This Data was Generated by Central Java Investment Platform</p>
</center>

<table class='table table-bordered'>
    <thead>
    <tr>
        <th>#</th>
        <th>Nama Perusahaan</th>
        <th>Sektor</th>
        <th>Kab/Kota</th>
        <th colspan="2">TTD</th>
    </tr>
    </thead>
    <tbody>
    @foreach($pesertas as $peserta)
        @if($peserta->meja_id)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td>{{$peserta->profil->nama_perusahaan}}, {{$peserta->profil->badan_hukum}} </td>
            <td>{{$peserta->sektor_interest}}</td>
            <td>{{$peserta->userId->admin->name}}</td>
            @if($loop->iteration % 2 == 0)
                <td></td>
                <td>{{$loop->iteration}}. </td>
            @else
                <td>{{$loop->iteration}}. </td>
                <td></td>
            @endif
        </tr>
        @endif
    @endforeach
    </tbody>
</table>
</body>
</html>
