<!DOCTYPE html>
<html>
<head>
    <title>Daftar Hadir</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<style type="text/css">
    table tr td,
    table tr th{
        font-size: 9pt;
    }
    .page_break { page-break-before: always; }
</style>

@foreach($pesertas as $meja => $peserta1)
    <center>
        <h5>This Data was Generated by Central Java Investment Platform</h5>
    </center>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>Nama Instansi</th>
            <th>Jabatan</th>
            <th>No Telp</th>
            <th colspan="2">TTD</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td></td>
            <td></td>
            <td></td>
            <td>1.</td>
            <td></td>
        </tr>
        <tr>
            <td>2</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>2.</td>
        </tr>
        </tbody>
    </table>
    <center>
        <h5>MEJA : {{$meja}}</h5>
    </center>
    <table class='table table-bordered'>
    <thead>
    <tr>
        <th>#</th>
        <th>Nama Perusahaan</th>
        <th>Sektor</th>
        <th>Kab/Kota</th>
        <th colspan="2">TTD</th>
    </tr>
    </thead>
    <tbody>
        @foreach($peserta1 as $peserta)

            @if($peserta->meja_id)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$peserta->profil->nama_perusahaan}}, {{$peserta->profil->badan_hukum}} </td>
                    <td>{{$peserta->sektor_interest}}</td>
                    <td>{{$peserta->userId->admin->name}}</td>
                    @if($loop->iteration % 2 == 0)
                        <td></td>
                        <td>{{$loop->iteration}}. </td>
                    @else
                        <td>{{$loop->iteration}}. </td>
                        <td></td>
                    @endif
                </tr>
            @endif
        @endforeach
    </tbody>
    </table>
    <div class="page_break"></div>
    <hr>
@endforeach

</body>
</html>
